import localFont from "next/font/local";
import { Poppins } from "next/font/google"
import "./globals.css";
import { Providers } from "./nextauth/Providers";

const poppins = Poppins({subsets:['latin'], weight:'400'})

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const revalidate = 1

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${poppins.className}`}
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
